#!/usr/bin/env python3
"""
Display Latest Performance Plots
This script displays the most recent performance visualizations generated by the system.
"""

import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pathlib import Path
import json

def display_latest_plots():
    """Display the latest performance plots"""
    
    # Get the performance_plots directory
    plots_dir = Path("performance_plots")
    
    if not plots_dir.exists():
        print("❌ Performance plots directory not found!")
        return
    
    print("🎨 Displaying Latest Performance Plots")
    print("=" * 50)
    
    # List of plot files to display
    plot_files = [
        "roc_curves_latest.png",
        "performance_comparison_annotated_latest.png",
        "confusion_matrices__base_model_latest.png",
        "confusion_matrices__ttt_enhanced_model_latest.png",
        "training_history_latest.png",
        "ttt_adaptation_latest.png",
        "blockchain_metrics_latest.png",
        "gas_usage_analysis_latest.png",
        "client_performance_latest.png"
    ]
    
    # Display each plot
    for plot_file in plot_files:
        plot_path = plots_dir / plot_file
        if plot_path.exists():
            print(f"\n📊 Displaying: {plot_file}")
            try:
                # Load and display the image
                img = mpimg.imread(plot_path)
                plt.figure(figsize=(12, 8))
                plt.imshow(img)
                plt.axis('off')
                plt.title(f"Performance Visualization: {plot_file.replace('_latest.png', '').replace('_', ' ').title()}")
                plt.tight_layout()
                plt.show()
                print(f"✅ {plot_file} displayed successfully")
            except Exception as e:
                print(f"❌ Failed to display {plot_file}: {str(e)}")
        else:
            print(f"⚠️ {plot_file} not found")
    
    # Display performance metrics JSON
    metrics_file = plots_dir / "performance_metrics_latest.json"
    if metrics_file.exists():
        print(f"\n📈 Performance Metrics:")
        print("=" * 30)
        try:
            with open(metrics_file, 'r') as f:
                metrics = json.load(f)
            
            # Display key metrics
            if 'base_model' in metrics:
                print(f"Base Model - Accuracy: {metrics['base_model'].get('accuracy', 'N/A'):.4f}")
                print(f"Base Model - F1-Score: {metrics['base_model'].get('f1_score', 'N/A'):.4f}")
                print(f"Base Model - ROC-AUC: {metrics['base_model'].get('roc_auc', 'N/A'):.4f}")
            
            if 'ttt_model' in metrics:
                print(f"TTT Model - Accuracy: {metrics['ttt_model'].get('accuracy', 'N/A'):.4f}")
                print(f"TTT Model - F1-Score: {metrics['ttt_model'].get('f1_score', 'N/A'):.4f}")
                print(f"TTT Model - ROC-AUC: {metrics['ttt_model'].get('roc_auc', 'N/A'):.4f}")
            
            if 'final_global_model' in metrics:
                print(f"Final Global Model - Accuracy: {metrics['final_global_model'].get('accuracy', 'N/A'):.4f}")
                print(f"Final Global Model - F1-Score: {metrics['final_global_model'].get('f1_score', 'N/A'):.4f}")
                print(f"Final Global Model - ROC-AUC: {metrics['final_global_model'].get('roc_auc', 'N/A'):.4f}")
                
        except Exception as e:
            print(f"❌ Failed to read metrics: {str(e)}")
    
    print(f"\n🎉 All available plots displayed!")
    print(f"📁 Plot files are saved in: {plots_dir.absolute()}")

if __name__ == "__main__":
    display_latest_plots()
