_wandb:
    value:
        cli_version: 0.22.2
        e:
            gq4iqvc0dmx56x832mvp3s2g1o866hny:
                codePath: optimize_hyperparameters.py
                codePathLocal: optimize_hyperparameters.py
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1196126580736"
                        used: "1084194062336"
                email: derjan06@gmail.com
                executable: C:\Users\Dspike\Documents\PhD\TNN\exp1\Tgnn_gpu\Scripts\python.exe
                git:
                    commit: 585e54f2643bd7dd118ef2a4017e946cd6565483
                    remote: https://github.com/DSpike/FedTTA-Z.git
                gpu: NVIDIA GeForce RTX 4070 Ti SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 8448
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4070 Ti SUPER
                      uuid: GPU-be2226ba-a64d-b0fb-7167-f5de669edc79
                host: DESKTOP-0DOBI2M
                memory:
                    total: "68519890944"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\Dspike\Documents\PhD\TNN\exp1\Tgnn\optimize_hyperparameters.py
                python: CPython 3.10.11
                root: C:\Users\Dspike\Documents\PhD\TNN\exp1\Tgnn
                startedAt: "2025-11-27T10:45:53.888891Z"
                writerId: gq4iqvc0dmx56x832mvp3s2g1o866hny
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
            "2":
                - 1
                - 5
                - 35
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.11
            "5": 0.22.2
            "8":
                - 2
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
direction:
    value: maximize
n_trials:
    value: 50
optimization_metric:
    value: ttt_zero_day_detection_rate
